var h,ba=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},ca=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:ba(a)}},da="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},ea="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,fa=function(a,b){if(b){var c=ea;a=a.split(".");
for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&da(c,a,{configurable:!0,writable:!0,value:b})}};
fa("Promise",function(a){function b(){this.ga=null}function c(g){return g instanceof e?g:new e(function(k){k(g)})}if(a)return a;b.prototype.gc=function(g){if(null==this.ga){this.ga=[];var k=this;this.hc(function(){k.ad()})}this.ga.push(g)};var d=ea.setTimeout;b.prototype.hc=function(g){d(g,0)};b.prototype.ad=function(){for(;this.ga&&this.ga.length;){var g=this.ga;this.ga=[];for(var k=0;k<g.length;++k){var l=g[k];g[k]=null;try{l()}catch(p){this.Vc(p)}}}this.ga=null};b.prototype.Vc=function(g){this.hc(function(){throw g;
})};var e=function(g){this.b=0;this.I=void 0;this.Ia=[];var k=this.Db();try{g(k.resolve,k.reject)}catch(l){k.reject(l)}};e.prototype.Db=function(){function g(p){return function(H){l||(l=!0,p.call(k,H))}}var k=this,l=!1;return{resolve:g(this.od),reject:g(this.Yb)}};e.prototype.od=function(g){if(g===this)this.Yb(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof e)this.qd(g);else{a:switch(typeof g){case "object":var k=null!=g;break a;case "function":k=!0;break a;default:k=!1}k?
this.nd(g):this.tc(g)}};e.prototype.nd=function(g){var k=void 0;try{k=g.then}catch(l){this.Yb(l);return}"function"==typeof k?this.rd(k,g):this.tc(g)};e.prototype.Yb=function(g){this.Kc(2,g)};e.prototype.tc=function(g){this.Kc(1,g)};e.prototype.Kc=function(g,k){if(0!=this.b)throw Error("Cannot settle("+g+", "+k+"): Promise already settled in state"+this.b);this.b=g;this.I=k;this.cd()};e.prototype.cd=function(){if(null!=this.Ia){for(var g=0;g<this.Ia.length;++g)f.gc(this.Ia[g]);this.Ia=null}};var f=
new b;e.prototype.qd=function(g){var k=this.Db();g.eb(k.resolve,k.reject)};e.prototype.rd=function(g,k){var l=this.Db();try{g.call(k,l.resolve,l.reject)}catch(p){l.reject(p)}};e.prototype.then=function(g,k){function l(O,aa){return"function"==typeof O?function(mb){try{p(O(mb))}catch(nb){H(nb)}}:aa}var p,H,ob=new e(function(O,aa){p=O;H=aa});this.eb(l(g,p),l(k,H));return ob};e.prototype["catch"]=function(g){return this.then(void 0,g)};e.prototype.eb=function(g,k){function l(){switch(p.b){case 1:g(p.I);
break;case 2:k(p.I);break;default:throw Error("Unexpected state: "+p.b);}}var p=this;null==this.Ia?f.gc(l):this.Ia.push(l)};e.resolve=c;e.reject=function(g){return new e(function(k,l){l(g)})};e.race=function(g){return new e(function(k,l){for(var p=ca(g),H=p.next();!H.done;H=p.next())c(H.value).eb(k,l)})};e.all=function(g){var k=ca(g),l=k.next();return l.done?c([]):new e(function(p,H){function ob(mb){return function(nb){O[mb]=nb;aa--;0==aa&&p(O)}}var O=[],aa=0;do O.push(void 0),aa++,c(l.value).eb(ob(O.length-
1),H),l=k.next();while(!l.done)})};return e});
var ha=ha||{},m=this||self,n=function(a){return void 0!==a},q=function(a){return"string"==typeof a},ia=function(a){return"number"==typeof a},ja=function(a,b,c){a=a.split(".");c=c||m;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&n(b)?c[d]=b:c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}},ka=function(a,b){a=a.split(".");b=b||m;for(var c=0;c<a.length;c++)if(b=b[a[c]],null==b)return null;return b},la=function(){},ma=function(a){var b=
typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b},r=function(a){return"array"==ma(a)},na=function(a){var b=ma(a);return"array"==b||"object"==b&&"number"==typeof a.length},t=function(a){return"function"==ma(a)},u=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},qa=function(a){return a[oa]||(a[oa]=++pa)},oa="closure_uid_"+(1E9*Math.random()>>>0),pa=0,ra=function(a,b,c){return a.call.apply(a.bind,arguments)},sa=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=
Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}},v=function(a,b,c){v=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ra:sa;return v.apply(null,arguments)},ta=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}},ua=
Date.now||function(){return+new Date},w=function(a,b){function c(){}c.prototype=b.prototype;a.T=b.prototype;a.prototype=new c;a.prototype.constructor=a};var x=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,x);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};w(x,Error);x.prototype.name="CustomError";var va;var wa=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");x.call(this,c+a[d])};w(wa,x);wa.prototype.name="AssertionError";
var xa=function(a,b,c,d){var e="Assertion failed";if(c){e+=": "+c;var f=d}else a&&(e+=": "+a,f=b);throw new wa(""+e,f||[]);},y=function(a,b,c){a||xa("",null,b,Array.prototype.slice.call(arguments,2));return a},ya=function(a,b){throw new wa("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));},za=function(a,b,c){ia(a)||xa("Expected number but got %s: %s.",[ma(a),a],b,Array.prototype.slice.call(arguments,2));return a},Aa=function(a,b,c){t(a)||xa("Expected function but got %s: %s.",[ma(a),
a],b,Array.prototype.slice.call(arguments,2))};var Ba=Array.prototype.indexOf?function(a,b){y(null!=a.length);return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(q(a))return q(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ca=Array.prototype.forEach?function(a,b,c){y(null!=a.length);Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=q(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Da=Array.prototype.some?function(a,b){y(null!=a.length);return Array.prototype.some.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=q(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1},Fa=function(a){a:{var b=Ea;for(var c=a.length,d=q(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return 0>b?null:q(a)?a.charAt(b):a[b]},Ga=function(a,b){b=Ba(a,b);var c;if(c=0<=b)y(null!=a.length),Array.prototype.splice.call(a,b,1);return c},Ha=function(a){return Array.prototype.concat.apply([],arguments)},Ia=function(a){var b=a.length;
if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},Ka=function(a,b){a.sort(b||Ja)},Ja=function(a,b){return a>b?1:a<b?-1:0};var La=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},Ma=function(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1},Na=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},Oa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),Pa=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Oa.length;f++)c=Oa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var Sa=function(a,b){this.Mc=a===Qa&&b||"";this.Sc=Ra};Sa.prototype.toString=function(){return"Const{"+this.Mc+"}"};var Ra={},Qa={},Ta=new Sa(Qa,"");var Ua=function(){this.Ec=""};Ua.prototype.toString=function(){return"SafeScript{"+this.Ec+"}"};Ua.prototype.ea=function(a){this.Ec=a;return this};(new Ua).ea("");var Wa=function(){this.Xb="";this.Pc=null;this.Tc=Va};Wa.prototype.toString=function(){return"TrustedResourceUrl{"+this.Xb+"}"};var Va={};var Xa=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]},Ya=function(a,b){return a<b?-1:a>b?1:0};var Za=function(){this.Gc=""};Za.prototype.toString=function(){return"SafeStyle{"+this.Gc+"}"};Za.prototype.ea=function(a){this.Gc=a;return this};(new Za).ea("");var $a=function(){this.Fc=""};$a.prototype.toString=function(){return"SafeStyleSheet{"+this.Fc+"}"};$a.prototype.ea=function(a){this.Fc=a;return this};(new $a).ea("");var z;a:{var ab=m.navigator;if(ab){var bb=ab.userAgent;if(bb){z=bb;break a}}z=""}var A=function(a){return-1!=z.indexOf(a)};var db=function(){this.Wb="";this.Rc=cb};db.prototype.toString=function(){return"SafeHtml{"+this.Wb+"}"};var fb=function(){var a=eb;if(a instanceof db&&a.constructor===db&&a.Rc===cb)return a.Wb;ya("expected object of type SafeHtml, got '"+a+"' of type "+ma(a));return"type_error:SafeHtml"},cb={};db.prototype.ea=function(a){this.Wb=a;return this};(new db).ea("<!DOCTYPE html>");var eb=(new db).ea("");(new db).ea("<br>");var gb=function(a){if(Ta instanceof Sa&&Ta.constructor===Sa&&Ta.Sc===Ra)var b=Ta.Mc;else ya("expected object of type Const, got '"+Ta+"'"),b="type_error:Const";var c=new Wa;c.Xb=b;a:{try{var d=a&&a.ownerDocument,e=d&&(d.defaultView||d.parentWindow);e=e||m;if(e.Element&&e.Location){var f=e;break a}}catch(k){}f=null}if(f&&"undefined"!=typeof f.HTMLIFrameElement&&(!a||!(a instanceof f.HTMLIFrameElement)&&(a instanceof f.Location||a instanceof f.Element))){if(u(a))try{var g=a.constructor.displayName||
a.constructor.name||Object.prototype.toString.call(a)}catch(k){g="<object could not be stringified>"}else g=void 0===a?"undefined":null===a?"null":typeof a;ya("Argument is not a %s (or a non-Element, non-Location mock); got: %s","HTMLIFrameElement",g)}c.Pc?b=c.Pc:(c instanceof Wa&&c.constructor===Wa&&c.Tc===Va?b=c.Xb:(ya("expected object of type TrustedResourceUrl, got '"+c+"' of type "+ma(c)),b="type_error:TrustedResourceUrl"),b=b.toString());a.src=b};var hb={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},ib={"'":"\\'"},jb=function(a){a=String(a);for(var b=['"'],c=0;c<a.length;c++){var d=a.charAt(c),e=d.charCodeAt(0),f=c+1,g;if(!(g=hb[d])){if(!(31<e&&127>e))if(d in ib)d=ib[d];else if(d in hb)d=ib[d]=hb[d];else{g=d.charCodeAt(0);if(31<g&&127>g)e=d;else{if(256>g){if(e="\\x",16>g||256<g)e+="0"}else e="\\u",4096>g&&(e+="0");e+=g.toString(16).toUpperCase()}d=ib[d]=e}g=d}b[f]=g}b.push('"');
return b.join("")},kb=function(a){isFinite(a)&&(a=String(a));return q(a)?/^\s*-?0x/i.test(a)?parseInt(a,16):parseInt(a,10):NaN};var lb=function(a,b){this.Qb=a.name||null;this.mc=a.xd;this.X={};for(a=0;a<b.length;a++){var c=b[a];this.X[c.U]=c}};lb.prototype.getName=function(){return this.Qb};lb.prototype.sa=function(){return this.mc?this.mc.v():null};var pb=function(a){a=Na(a.X);Ka(a,function(b,c){return b.U-c.U});return a};var qb=function(a,b,c){this.m=a;y(!/[^0-9]/.test(b));this.U=b;this.Qb=c.name;this.Nb=!!c.Ad;this.ba=c.Ib;this.Rb=c.type};qb.prototype.sa=function(){return this.m.prototype.v()};qb.prototype.getName=function(){return this.Qb};var B=function(){this.F={};this.X=this.v().X;this.G=this.yc=null},rb=function(a,b,c){c=c||a;for(var d in a.F){var e=Number(d);a.X[e]||b.call(c,e,a.F[d])}};h=B.prototype;h.has=function(a){y(a.sa()==this.v(),"The current message does not contain the given field");return null!=this.F[a.U]};
h.get=function(a,b){y(a.sa()==this.v(),"The current message does not contain the given field");var c=a.U;a=sb(this,c);this.X[c].Nb?(b=b||0,y(0<=b&&b<a.length,"Given index %s is out of bounds.  Repeated field length: %s",b,a.length),b=a[b]):b=a;return b};h.set=function(a,b){y(a.sa()==this.v(),"The current message does not contain the given field");C(this,a.U,b)};h.add=function(a,b){y(a.sa()==this.v(),"The current message does not contain the given field");tb(this,a.U,b)};
h.clear=function(a){y(a.sa()==this.v(),"The current message does not contain the given field");a=a.U;delete this.F[a];this.G&&delete this.G[a]};
var ub=function(a,b){y(a.constructor==b.constructor,"The source message must have the same type.");for(var c=pb(a.v()),d=0;d<c.length;d++){var e=c[d],f=e.U;if(null!=b.F[f]){a.G&&delete a.G[e.U];var g=11==e.ba||10==e.ba;if(e.Nb){e=sb(b,f)||[];for(var k=0;k<e.length;k++)tb(a,f,g?e[k].clone():e[k])}else e=sb(b,f),g?(g=sb(a,f))?ub(g,e):C(a,f,e.clone()):C(a,f,e)}}};
B.prototype.clone=function(){var a=new this.constructor;y(a.constructor==this.constructor,"The source message must have the same type.");a!=this&&(a.F={},a.G&&(a.G={}),ub(a,this));return a};
var sb=function(a,b){var c=a.F[b];return null==c?null:a.yc?b in a.G?a.G[b]:(c=a.yc.yd(a,a.X[b],c),a.G[b]=c):c},C=function(a,b,c){var d=a.X[b];14==d.ba?za(c):y(Object(c).constructor==d.Rb);a.F[b]=c;a.G&&(a.G[b]=c)},tb=function(a,b,c){var d=a.X[b];14==d.ba?za(c):y(Object(c).constructor==d.Rb);a.F[b]||(a.F[b]=[]);a.F[b].push(c);a.G&&delete a.G[b]},vb=function(a,b){var c=[],d=b[0],e;for(e in b)0!=e&&c.push(new qb(a,e,b[e]));return new lb(d,c)};var D=function(){B.call(this)};w(D,B);var wb=null,xb=function(){B.call(this)};w(xb,B);var yb=null;D.prototype.v=function(){var a=wb;a||(wb=a=vb(D,{0:{name:"Version",dd:"buzz.channel.Version"},1:{name:"major_version",Ib:5,type:Number},2:{name:"minor_version",Ib:5,type:Number}}));return a};D.v=D.prototype.v;xb.prototype.v=function(){var a=yb;a||(yb=a=vb(xb,{0:{name:"ProtocolVersion",dd:"buzz.channel.ProtocolVersion"},1:{name:"version",Ib:11,type:D}}));return a};xb.v=xb.prototype.v;/*
 Copyright (c) Microsoft Corporation. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 this file except in compliance with the License. You may obtain a copy of the
 License at http://www.apache.org/licenses/LICENSE-2.0

 THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
 WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
 MERCHANTABLITY OR NON-INFRINGEMENT.

 See the Apache Version 2.0 License for specific language governing permissions
 and limitations under the License.
*/
var zb="StopIteration"in m?m.StopIteration:{message:"StopIteration",stack:""},Ab=function(){};Ab.prototype.next=function(){throw zb;};Ab.prototype.zb=function(){return this};var Bb=function(a,b){this.l={};this.c=[];this.Ya=this.g=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.addAll(a)};h=Bb.prototype;h.L=function(){Cb(this);for(var a=[],b=0;b<this.c.length;b++)a.push(this.l[this.c[b]]);return a};h.ca=function(){Cb(this);return this.c.concat()};h.Da=function(a){return Db(this.l,a)};h.clear=function(){this.l={};this.Ya=this.g=this.c.length=0};
h.remove=function(a){return Db(this.l,a)?(delete this.l[a],this.g--,this.Ya++,this.c.length>2*this.g&&Cb(this),!0):!1};var Cb=function(a){if(a.g!=a.c.length){for(var b=0,c=0;b<a.c.length;){var d=a.c[b];Db(a.l,d)&&(a.c[c++]=d);b++}a.c.length=c}if(a.g!=a.c.length){var e={};for(c=b=0;b<a.c.length;)d=a.c[b],Db(e,d)||(a.c[c++]=d,e[d]=1),b++;a.c.length=c}};h=Bb.prototype;h.get=function(a,b){return Db(this.l,a)?this.l[a]:b};
h.set=function(a,b){Db(this.l,a)||(this.g++,this.c.push(a),this.Ya++);this.l[a]=b};h.addAll=function(a){if(a instanceof Bb)for(var b=a.ca(),c=0;c<b.length;c++)this.set(b[c],a.get(b[c]));else for(b in a)this.set(b,a[b])};h.forEach=function(a,b){for(var c=this.ca(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};h.clone=function(){return new Bb(this)};
h.zb=function(a){Cb(this);var b=0,c=this.Ya,d=this,e=new Ab;e.next=function(){if(c!=d.Ya)throw Error("The map has changed since the iterator was created");if(b>=d.c.length)throw zb;var f=d.c[b++];return a?f:d.l[f]};return e};var Db=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var Eb=function(a){if(a.L&&"function"==typeof a.L)return a.L();if(q(a))return a.split("");if(na(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Na(a)},Fb=function(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(na(a)||q(a))Ca(a,b,c);else{if(a.ca&&"function"==typeof a.ca)var d=a.ca();else if(a.L&&"function"==typeof a.L)d=void 0;else if(na(a)||q(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else for(f in d=[],e=0,a)d[e++]=f;e=Eb(a);f=e.length;for(var g=
0;g<f;g++)b.call(c,e[g],d&&d[g],a)}};var Gb=function(a){this.l=new Bb;a&&this.addAll(a)},Hb=function(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+qa(a):b.substr(0,1)+a};h=Gb.prototype;h.add=function(a){this.l.set(Hb(a),a)};h.addAll=function(a){a=Eb(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c])};h.Sa=function(a){a=Eb(a);for(var b=a.length,c=0;c<b;c++)this.remove(a[c])};h.remove=function(a){return this.l.remove(Hb(a))};h.clear=function(){this.l.clear()};h.contains=function(a){return this.l.Da(Hb(a))};h.L=function(){return this.l.L()};
h.clone=function(){return new Gb(this)};h.zb=function(){return this.l.zb(!1)};new Gb([1,2,3]);new Gb([1,2]);var Ib=function(a){Ib[" "](a);return a};Ib[" "]=la;var Kb=function(a,b){var c=Jb;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var Lb=A("Opera"),Mb=A("Trident")||A("MSIE"),Nb=A("Edge"),Ob=A("Gecko")&&!(-1!=z.toLowerCase().indexOf("webkit")&&!A("Edge"))&&!(A("Trident")||A("MSIE"))&&!A("Edge"),Pb=-1!=z.toLowerCase().indexOf("webkit")&&!A("Edge"),Qb=A("Macintosh"),Rb=A("Windows"),Sb=A("Android"),Tb=A("iPhone")&&!A("iPod")&&!A("iPad"),Ub=A("iPad"),Vb=A("iPod"),Wb=function(){var a=m.document;return a?a.documentMode:void 0},Xb;
a:{var Yb="",Zb=function(){var a=z;if(Ob)return/rv:([^\);]+)(\)|;)/.exec(a);if(Nb)return/Edge\/([\d\.]+)/.exec(a);if(Mb)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Pb)return/WebKit\/(\S+)/.exec(a);if(Lb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Zb&&(Yb=Zb?Zb[1]:"");if(Mb){var $b=Wb();if(null!=$b&&$b>parseFloat(Yb)){Xb=String($b);break a}}Xb=Yb}
var ac=Xb,Jb={},bc=function(a){return Kb(a,function(){for(var b=0,c=Xa(String(ac)).split("."),d=Xa(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",k=d[f]||"";do{g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];if(0==g[0].length&&0==k[0].length)break;b=Ya(0==g[1].length?0:parseInt(g[1],10),0==k[1].length?0:parseInt(k[1],10))||Ya(0==g[2].length,0==k[2].length)||Ya(g[2],k[2]);g=g[3];k=k[3]}while(0==b)}return 0<=b})},cc;
cc=m.document&&Mb?Wb():void 0;var dc=Object.freeze||function(a){return a};var ec=function(){this.Hc=ua()},fc=null;ec.prototype.set=function(a){this.Hc=a};ec.prototype.reset=function(){this.set(ua())};ec.prototype.get=function(){return this.Hc};var gc=function(){fc||(fc=new ec)},hc=function(){fc||(fc=new ec)};w(hc,gc);var E=function(){this.ia=this.ia;this.va=this.va};E.prototype.ia=!1;E.prototype.Eb=function(){this.ia||(this.ia=!0,this.i())};var ic=function(a,b){a.ia?n(void 0)?b.call(void 0):b():(a.va||(a.va=[]),a.va.push(n(void 0)?v(b,void 0):b))};E.prototype.i=function(){if(this.va)for(;this.va.length;)this.va.shift()()};var F=function(a){a&&"function"==typeof a.Eb&&a.Eb()};var jc=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.ya=!1;this.Jc=!0};jc.prototype.stopPropagation=function(){this.ya=!0};jc.prototype.preventDefault=function(){this.defaultPrevented=!0;this.Jc=!1};var kc;(kc=!Mb)||(kc=9<=Number(cc));var lc=kc,mc=Mb&&!bc("9"),nc=function(){if(!m.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{m.addEventListener("test",la,b),m.removeEventListener("test",la,b)}catch(c){}return a}();var G=function(a,b){jc.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.key="";this.charCode=this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.ja=null;a&&this.Lb(a,b)};w(G,jc);var oc=dc({2:"touch",3:"pen",4:"mouse"});
G.prototype.Lb=function(a,b){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;if(b=a.relatedTarget){if(Ob){a:{try{Ib(b.nodeName);var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=
d.screenY||0):(this.offsetX=Pb||void 0!==a.offsetX?a.offsetX:a.layerX,this.offsetY=Pb||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=
a.pointerId||0;this.pointerType=q(a.pointerType)?a.pointerType:oc[a.pointerType]||"";this.state=a.state;this.ja=a;a.defaultPrevented&&this.preventDefault()};G.prototype.stopPropagation=function(){G.T.stopPropagation.call(this);this.ja.stopPropagation?this.ja.stopPropagation():this.ja.cancelBubble=!0};
G.prototype.preventDefault=function(){G.T.preventDefault.call(this);var a=this.ja;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,mc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var pc="closure_listenable_"+(1E6*Math.random()|0),qc=function(a){return!(!a||!a[pc])},rc=0;var sc=function(a,b,c,d,e){this.listener=a;this.ob=null;this.src=b;this.type=c;this.capture=!!d;this.ta=e;this.key=++rc;this.Ka=this.cb=!1},tc=function(a){a.Ka=!0;a.listener=null;a.ob=null;a.src=null;a.ta=null};var I=function(a){this.src=a;this.w={};this.Xa=0};I.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.w[f];a||(a=this.w[f]=[],this.Xa++);var g=uc(a,b,d,e);-1<g?(b=a[g],c||(b.cb=!1)):(b=new sc(b,this.src,f,!!d,e),b.cb=c,a.push(b));return b};I.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.w))return!1;var e=this.w[a];b=uc(e,b,c,d);return-1<b?(tc(e[b]),y(null!=e.length),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.w[a],this.Xa--),!0):!1};
var vc=function(a,b){var c=b.type;c in a.w&&Ga(a.w[c],b)&&(tc(b),0==a.w[c].length&&(delete a.w[c],a.Xa--))};I.prototype.Sa=function(a){a=a&&a.toString();var b=0,c;for(c in this.w)if(!a||c==a){for(var d=this.w[c],e=0;e<d.length;e++)++b,tc(d[e]);delete this.w[c];this.Xa--}};I.prototype.Ma=function(a,b,c,d){a=this.w[a.toString()];var e=-1;a&&(e=uc(a,b,c,d));return-1<e?a[e]:null};
I.prototype.hasListener=function(a,b){var c=n(a),d=c?a.toString():"",e=n(b);return Ma(this.w,function(f){for(var g=0;g<f.length;++g)if(!(c&&f[g].type!=d||e&&f[g].capture!=b))return!0;return!1})};var uc=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.Ka&&f.listener==b&&f.capture==!!c&&f.ta==d)return e}return-1};var wc="closure_lm_"+(1E6*Math.random()|0),xc={},yc=0,Ac=function(a,b,c,d,e){if(d&&d.once)return zc(a,b,c,d,e);if(r(b)){for(var f=0;f<b.length;f++)Ac(a,b[f],c,d,e);return null}c=Bc(c);return qc(a)?a.Qa(b,c,u(d)?!!d.capture:!!d,e):Cc(a,b,c,!1,d,e)},Cc=function(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var g=u(e)?!!e.capture:!!e,k=Dc(a);k||(a[wc]=k=new I(a));c=k.add(b,c,d,g,f);if(c.ob)return c;d=Ec();c.ob=d;d.src=a;d.listener=c;if(a.addEventListener)nc||(e=g),void 0===e&&(e=!1),a.addEventListener(b.toString(),
d,e);else if(a.attachEvent)a.attachEvent(Fc(b.toString()),d);else if(a.addListener&&a.removeListener)y("change"===b,"MediaQueryList only has a change event"),a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");yc++;return c},Ec=function(){var a=Gc,b=lc?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b},zc=function(a,b,c,d,e){if(r(b)){for(var f=0;f<b.length;f++)zc(a,b[f],c,d,e);return null}c=Bc(c);return qc(a)?
a.Ob(b,c,u(d)?!!d.capture:!!d,e):Cc(a,b,c,!0,d,e)},Hc=function(a,b,c,d,e){if(r(b))for(var f=0;f<b.length;f++)Hc(a,b[f],c,d,e);else d=u(d)?!!d.capture:!!d,c=Bc(c),qc(a)?a.ec(b,c,d,e):a&&(a=Dc(a))&&(b=a.Ma(b,c,d,e))&&Ic(b)},Ic=function(a){if(!ia(a)&&a&&!a.Ka){var b=a.src;if(qc(b))vc(b.O,a);else{var c=a.type,d=a.ob;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Fc(c),d):b.addListener&&b.removeListener&&b.removeListener(d);yc--;(c=Dc(b))?(vc(c,a),0==c.Xa&&(c.src=
null,b[wc]=null)):tc(a)}}},Jc=function(a,b,c,d,e){c=Bc(c);d=!!d;return qc(a)?a.Ma(b,c,d,e):a?(a=Dc(a))?a.Ma(b,c,d,e):null:null},Fc=function(a){return a in xc?xc[a]:xc[a]="on"+a},Lc=function(a,b,c,d){var e=!0;if(a=Dc(a))if(b=a.w[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.Ka&&(f=Kc(f,d),e=e&&!1!==f)}return e},Kc=function(a,b){var c=a.listener,d=a.ta||a.src;a.cb&&Ic(a);return c.call(d,b)},Gc=function(a,b){if(a.Ka)return!0;if(!lc){var c=b||ka("window.event");b=new G(c,
this);var d=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var e=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(g){e=!0}if(e||void 0==c.returnValue)c.returnValue=!0}c=[];for(e=b.currentTarget;e;e=e.parentNode)c.push(e);a=a.type;for(e=c.length-1;!b.ya&&0<=e;e--){b.currentTarget=c[e];var f=Lc(c[e],a,!0,b);d=d&&f}for(e=0;!b.ya&&e<c.length;e++)b.currentTarget=c[e],f=Lc(c[e],a,!1,b),d=d&&f}return d}return Kc(a,new G(b,this))},Dc=function(a){a=a[wc];return a instanceof I?a:null},Mc="__closure_events_fn_"+
(1E9*Math.random()>>>0),Bc=function(a){y(a,"Listener can not be null.");if(t(a))return a;y(a.handleEvent,"An object listener must have handleEvent method.");a[Mc]||(a[Mc]=function(b){return a.handleEvent(b)});return a[Mc]};var J=function(){E.call(this);this.O=new I(this);this.Uc=this;this.Tb=null};w(J,E);J.prototype[pc]=!0;h=J.prototype;h.addEventListener=function(a,b,c,d){Ac(this,a,b,c,d)};h.removeEventListener=function(a,b,c,d){Hc(this,a,b,c,d)};
h.dispatchEvent=function(a){Nc(this);var b=this.Tb;if(b){var c=[];for(var d=1;b;b=b.Tb)c.push(b),y(1E3>++d,"infinite loop")}b=this.Uc;d=a.type||a;if(q(a))a=new jc(a,b);else if(a instanceof jc)a.target=a.target||b;else{var e=a;a=new jc(d,b);Pa(a,e)}e=!0;if(c)for(var f=c.length-1;!a.ya&&0<=f;f--){var g=a.currentTarget=c[f];e=Oc(g,d,!0,a)&&e}a.ya||(g=a.currentTarget=b,e=Oc(g,d,!0,a)&&e,a.ya||(e=Oc(g,d,!1,a)&&e));if(c)for(f=0;!a.ya&&f<c.length;f++)g=a.currentTarget=c[f],e=Oc(g,d,!1,a)&&e;return e};
h.i=function(){J.T.i.call(this);this.O&&this.O.Sa(void 0);this.Tb=null};h.Qa=function(a,b,c,d){Nc(this);return this.O.add(String(a),b,!1,c,d)};h.Ob=function(a,b,c,d){return this.O.add(String(a),b,!0,c,d)};h.ec=function(a,b,c,d){this.O.remove(String(a),b,c,d)};var Oc=function(a,b,c,d){b=a.O.w[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.Ka&&g.capture==c){var k=g.listener,l=g.ta||g.src;g.cb&&vc(a.O,g);e=!1!==k.call(l,d)&&e}}return e&&0!=d.Jc};
J.prototype.Ma=function(a,b,c,d){return this.O.Ma(String(a),b,c,d)};J.prototype.hasListener=function(a,b){return this.O.hasListener(n(a)?String(a):void 0,b)};var Nc=function(a){y(a.O,"Event target is not initialized. Did you call the superclass (goog.events.EventTarget) constructor?")};var Pc=function(){this.pb=void 0};Pc.prototype.sb=function(a){var b=[];Qc(this,a,b);return b.join("")};
var Qc=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(r(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),e=d[f],Qc(a,a.pb?a.pb.call(d,String(f),e):e,c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");f="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(e=b[d],"function"!=typeof e&&(c.push(f),Rc(d,c),c.push(":"),Qc(a,a.pb?a.pb.call(b,d,e):e,c),f=","));c.push("}");return}}switch(typeof b){case "string":Rc(b,
c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("Unknown type: "+typeof b);}}},Sc={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},Tc=/\uffff/.test("\uffff")?/[\\"\x00-\x1f\x7f-\uffff]/g:/[\\"\x00-\x1f\x7f-\xff]/g,Rc=function(a,b){b.push('"',a.replace(Tc,function(c){var d=Sc[c];d||(d="\\u"+(c.charCodeAt(0)|65536).toString(16).substr(1),
Sc[c]=d);return d}),'"')};var L=function(a){var b=K.j;b&&b.info(a,void 0)},M=function(a,b){a&&a.zd(b,void 0)};var Uc=function(a,b){this.gd=100;this.Zc=a;this.md=b;this.mb=0;this.ib=null};Uc.prototype.get=function(){if(0<this.mb){this.mb--;var a=this.ib;this.ib=a.next;a.next=null}else a=this.Zc();return a};Uc.prototype.put=function(a){this.md(a);this.mb<this.gd&&(this.mb++,a.next=this.ib,this.ib=a)};var Vc=function(a){m.setTimeout(function(){throw a;},0)},Wc,Xc=function(){var a=m.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!A("Presto")&&(a=function(){var e=document.createElement("IFRAME");e.style.display="none";gb(e);document.documentElement.appendChild(e);var f=e.contentWindow;e=f.document;e.open();e.write(fb());e.close();var g="callImmediate"+Math.random(),k="file:"==f.location.protocol?"*":f.location.protocol+"//"+f.location.host;
e=v(function(l){if(("*"==k||l.origin==k)&&l.data==g)this.port1.onmessage()},this);f.addEventListener("message",e,!1);this.port1={};this.port2={postMessage:function(){f.postMessage(g,k)}}});if("undefined"!==typeof a&&!A("Trident")&&!A("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(n(c.next)){c=c.next;var e=c.lc;c.lc=null;e()}};return function(e){d.next={lc:e};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("SCRIPT")?
function(e){var f=document.createElement("SCRIPT");f.onreadystatechange=function(){f.onreadystatechange=null;f.parentNode.removeChild(f);f=null;e();e=null};document.documentElement.appendChild(f)}:function(e){m.setTimeout(e,0)}};var Yc=function(){this.wb=this.Aa=null},$c=new Uc(function(){return new Zc},function(a){a.reset()});Yc.prototype.add=function(a,b){var c=$c.get();c.set(a,b);this.wb?this.wb.next=c:(y(!this.Aa),this.Aa=c);this.wb=c};Yc.prototype.remove=function(){var a=null;this.Aa&&(a=this.Aa,this.Aa=this.Aa.next,this.Aa||(this.wb=null),a.next=null);return a};var Zc=function(){this.next=this.scope=this.Jb=null};Zc.prototype.set=function(a,b){this.Jb=a;this.scope=b;this.next=null};
Zc.prototype.reset=function(){this.next=this.scope=this.Jb=null};var ed=function(a,b){ad||bd();cd||(ad(),cd=!0);dd.add(a,b)},ad,bd=function(){if(m.Promise&&m.Promise.resolve){var a=m.Promise.resolve(void 0);ad=function(){a.then(fd)}}else ad=function(){var b=fd;!t(m.setImmediate)||m.Window&&m.Window.prototype&&!A("Edge")&&m.Window.prototype.setImmediate==m.setImmediate?(Wc||(Wc=Xc()),Wc(b)):m.setImmediate(b)}},cd=!1,dd=new Yc,fd=function(){for(var a;a=dd.remove();){try{a.Jb.call(a.scope)}catch(b){Vc(b)}$c.put(a)}cd=!1};var gd=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var N=function(a){this.b=0;this.I=void 0;this.Ca=this.$=this.m=null;this.hb=this.Hb=!1;if(a!=la)try{var b=this;a.call(void 0,function(c){hd(b,2,c)},function(c){if(!(c instanceof id))try{if(c instanceof Error)throw c;throw Error("Promise rejected.");}catch(d){}hd(b,3,c)})}catch(c){hd(this,3,c)}},jd=function(){this.next=this.context=this.Ha=this.wa=this.oa=null;this.$a=!1};jd.prototype.reset=function(){this.context=this.Ha=this.wa=this.oa=null;this.$a=!1};
var kd=new Uc(function(){return new jd},function(a){a.reset()}),ld=function(a,b,c){var d=kd.get();d.wa=a;d.Ha=b;d.context=c;return d};N.prototype.then=function(a,b,c){null!=a&&Aa(a,"opt_onFulfilled should be a function.");null!=b&&Aa(b,"opt_onRejected should be a function. Did you pass opt_context as the second argument instead of the third?");return md(this,t(a)?a:null,t(b)?b:null,c)};N.prototype.$goog_Thenable=!0;
N.prototype.cancel=function(a){0==this.b&&ed(function(){var b=new id(a);nd(this,b)},this)};
var nd=function(a,b){if(0==a.b)if(a.m){var c=a.m;if(c.$){for(var d=0,e=null,f=null,g=c.$;g&&(g.$a||(d++,g.oa==a&&(e=g),!(e&&1<d)));g=g.next)e||(f=g);e&&(0==c.b&&1==d?nd(c,b):(f?(d=f,y(c.$),y(null!=d),d.next==c.Ca&&(c.Ca=d),d.next=d.next.next):od(c),pd(c,e,3,b)))}a.m=null}else hd(a,3,b)},rd=function(a,b){a.$||2!=a.b&&3!=a.b||qd(a);y(null!=b.wa);a.Ca?a.Ca.next=b:a.$=b;a.Ca=b},md=function(a,b,c,d){var e=ld(null,null,null);e.oa=new N(function(f,g){e.wa=b?function(k){try{var l=b.call(d,k);f(l)}catch(p){g(p)}}:
f;e.Ha=c?function(k){try{var l=c.call(d,k);!n(l)&&k instanceof id?g(k):f(l)}catch(p){g(p)}}:g});e.oa.m=a;rd(a,e);return e.oa};N.prototype.ud=function(a){y(1==this.b);this.b=0;hd(this,2,a)};N.prototype.vd=function(a){y(1==this.b);this.b=0;hd(this,3,a)};
var hd=function(a,b,c){if(0==a.b){a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.b=1;a:{var d=c,e=a.ud,f=a.vd;if(d instanceof N){null!=e&&Aa(e,"opt_onFulfilled should be a function.");null!=f&&Aa(f,"opt_onRejected should be a function. Did you pass opt_context as the second argument instead of the third?");rd(d,ld(e||la,f||null,a));var g=!0}else if(gd(d))d.then(e,f,a),g=!0;else{if(u(d))try{var k=d.then;if(t(k)){sd(d,k,e,f,a);g=!0;break a}}catch(l){f.call(a,l);g=!0;break a}g=!1}}g||
(a.I=c,a.b=b,a.m=null,qd(a),3!=b||c instanceof id||td(a,c))}},sd=function(a,b,c,d,e){var f=!1,g=function(l){f||(f=!0,c.call(e,l))},k=function(l){f||(f=!0,d.call(e,l))};try{b.call(a,g,k)}catch(l){k(l)}},qd=function(a){a.Hb||(a.Hb=!0,ed(a.bd,a))},od=function(a){var b=null;a.$&&(b=a.$,a.$=b.next,b.next=null);a.$||(a.Ca=null);null!=b&&y(null!=b.wa);return b};N.prototype.bd=function(){for(var a;a=od(this);)pd(this,a,this.b,this.I);this.Hb=!1};
var pd=function(a,b,c,d){if(3==c&&b.Ha&&!b.$a)for(;a&&a.hb;a=a.m)a.hb=!1;if(b.oa)b.oa.m=null,ud(b,c,d);else try{b.$a?b.wa.call(b.context):ud(b,c,d)}catch(e){vd.call(null,e)}kd.put(b)},ud=function(a,b,c){2==b?a.wa.call(a.context,c):a.Ha&&a.Ha.call(a.context,c)},td=function(a,b){a.hb=!0;ed(function(){a.hb&&vd.call(null,b)})},vd=Vc,id=function(a){x.call(this,a)};w(id,x);id.prototype.name="cancel";var wd=function(a,b){J.call(this);this.Ga=a||1;this.Wa=b||m;this.jc=v(this.td,this);this.xc=ua()};w(wd,J);h=wd.prototype;h.enabled=!1;h.V=null;h.setInterval=function(a){this.Ga=a;this.V&&this.enabled?(this.stop(),this.start()):this.V&&this.stop()};h.td=function(){if(this.enabled){var a=ua()-this.xc;0<a&&a<.8*this.Ga?this.V=this.Wa.setTimeout(this.jc,this.Ga-a):(this.V&&(this.Wa.clearTimeout(this.V),this.V=null),this.dispatchEvent("tick"),this.enabled&&(this.stop(),this.start()))}};
h.start=function(){this.enabled=!0;this.V||(this.V=this.Wa.setTimeout(this.jc,this.Ga),this.xc=ua())};h.stop=function(){this.enabled=!1;this.V&&(this.Wa.clearTimeout(this.V),this.V=null)};h.i=function(){wd.T.i.call(this);this.stop();delete this.Wa};var xd=function(a,b,c){if(t(a))c&&(a=v(a,c));else if(a&&"function"==typeof a.handleEvent)a=v(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:m.setTimeout(a,b||0)};var P=function(a){E.call(this);this.Fa=a;this.c={}};w(P,E);var yd=[];P.prototype.Qa=function(a,b,c,d){r(b)||(b&&(yd[0]=b.toString()),b=yd);for(var e=0;e<b.length;e++){var f=Ac(a,b[e],c||this.handleEvent,d||!1,this.Fa||this);if(!f)break;this.c[f.key]=f}return this};P.prototype.Ob=function(a,b,c,d){return zd(this,a,b,c,d)};var zd=function(a,b,c,d,e,f){if(r(c))for(var g=0;g<c.length;g++)zd(a,b,c[g],d,e,f);else{b=zc(b,c,d||a.handleEvent,e,f||a.Fa||a);if(!b)return a;a.c[b.key]=b}return a};
P.prototype.ec=function(a,b,c,d,e){if(r(b))for(var f=0;f<b.length;f++)this.ec(a,b[f],c,d,e);else if(a=Jc(a,b,c||this.handleEvent,u(d)?!!d.capture:!!d,e||this.Fa||this))Ic(a),delete this.c[a.key]};P.prototype.Sa=function(){La(this.c,function(a,b){this.c.hasOwnProperty(b)&&Ic(a)},this);this.c={}};P.prototype.i=function(){P.T.i.call(this);this.Sa()};P.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};var Ad=function(){};Ad.prototype.kc=null;var Cd=function(a){var b;(b=a.kc)||(b={},Bd(a)&&(b[0]=!0,b[1]=!0),b=a.kc=b);return b};var Dd,Ed=function(){};w(Ed,Ad);var Fd=function(a){return(a=Bd(a))?new ActiveXObject(a):new XMLHttpRequest},Bd=function(a){if(!a.vc&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.vc=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.vc};Dd=new Ed;var Gd=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,Hd=function(a){var b=a.match(Gd);a=b[1];var c=b[2],d=b[3];b=b[4];var e="";a&&(e+=a+":");d&&(e+="//",c&&(e+=c+"@"),e+=d,b&&(e+=":"+b));return e},Id=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};var Q=function(a){this.aa=this.za=this.ma="";this.Ja=null;this.ra=this.Z="";this.M=this.fd=!1;if(a instanceof Q){this.M=n(void 0)?void 0:a.M;Jd(this,a.ma);var b=a.za;R(this);this.za=b;b=a.aa;R(this);this.aa=b;Kd(this,a.Ja);b=a.Z;R(this);this.Z=b;Ld(this,a.A.clone());a=a.ra;R(this);this.ra=a}else a&&(b=String(a).match(Gd))?(this.M=!1,Jd(this,b[1]||"",!0),a=b[2]||"",R(this),this.za=Md(a),a=b[3]||"",R(this),this.aa=Md(a,!0),Kd(this,b[4]),a=b[5]||"",R(this),this.Z=Md(a,!0),Ld(this,b[6]||"",!0),a=b[7]||
"",R(this),this.ra=Md(a)):(this.M=!1,this.A=new Nd(null,this.M))};
Q.prototype.toString=function(){var a=[],b=this.ma;b&&a.push(Od(b,Pd,!0),":");var c=this.aa;if(c||"file"==b)a.push("//"),(b=this.za)&&a.push(Od(b,Pd,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.Ja,null!=c&&a.push(":",String(c));if(c=this.Z)this.aa&&"/"!=c.charAt(0)&&a.push("/"),a.push(Od(c,"/"==c.charAt(0)?Qd:Rd,!0));(c=this.A.toString())&&a.push("?",c);(c=this.ra)&&a.push("#",Od(c,Sd));return a.join("")};
Q.prototype.resolve=function(a){var b=this.clone(),c=!!a.ma;c?Jd(b,a.ma):c=!!a.za;if(c){var d=a.za;R(b);b.za=d}else c=!!a.aa;c?(d=a.aa,R(b),b.aa=d):c=null!=a.Ja;d=a.Z;if(c)Kd(b,a.Ja);else if(c=!!a.Z){if("/"!=d.charAt(0))if(this.aa&&!this.Z)d="/"+d;else{var e=b.Z.lastIndexOf("/");-1!=e&&(d=b.Z.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var f=[],g=0;g<e.length;){var k=e[g++];"."==k?d&&g==e.length&&f.push(""):
".."==k?((1<f.length||1==f.length&&""!=f[0])&&f.pop(),d&&g==e.length&&f.push("")):(f.push(k),d=!0)}d=f.join("/")}else d=e}c?(R(b),b.Z=d):c=""!==a.A.toString();c?Ld(b,a.A.clone()):c=!!a.ra;c&&(a=a.ra,R(b),b.ra=a);return b};Q.prototype.clone=function(){return new Q(this)};
var Jd=function(a,b,c){R(a);a.ma=c?Md(b,!0):b;a.ma&&(a.ma=a.ma.replace(/:$/,""))},Kd=function(a,b){R(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.Ja=b}else a.Ja=null},Ld=function(a,b,c){R(a);b instanceof Nd?(a.A=b,a.A.bc(a.M)):(c||(b=Od(b,Td)),a.A=new Nd(b,a.M))};Q.prototype.getQuery=function(){return this.A.toString()};Q.prototype.removeParameter=function(a){R(this);this.A.remove(a);return this};
var R=function(a){if(a.fd)throw Error("Tried to modify a read-only Uri");};Q.prototype.bc=function(a){this.M=a;this.A&&this.A.bc(a)};
var Md=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},Od=function(a,b,c){return q(a)?(a=encodeURI(a).replace(b,Ud),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},Ud=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Pd=/[#\/\?@]/g,Rd=/[#\?:]/g,Qd=/[#\?]/g,Td=/[#\?@]/g,Sd=/#/g,Nd=function(a,b){this.g=this.f=null;this.H=a||null;this.M=!!b},S=function(a){a.f||(a.f=new Bb,a.g=0,a.H&&Id(a.H,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g,
" ")),c)}))};h=Nd.prototype;h.add=function(a,b){S(this);this.H=null;a=Vd(this,a);var c=this.f.get(a);c||this.f.set(a,c=[]);c.push(b);this.g=za(this.g)+1;return this};h.remove=function(a){S(this);a=Vd(this,a);return this.f.Da(a)?(this.H=null,this.g=za(this.g)-this.f.get(a).length,this.f.remove(a)):!1};h.clear=function(){this.f=this.H=null;this.g=0};h.Da=function(a){S(this);a=Vd(this,a);return this.f.Da(a)};
h.forEach=function(a,b){S(this);this.f.forEach(function(c,d){Ca(c,function(e){a.call(b,e,d,this)},this)},this)};h.ca=function(){S(this);for(var a=this.f.L(),b=this.f.ca(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};h.L=function(a){S(this);var b=[];if(q(a))this.Da(a)&&(b=Ha(b,this.f.get(Vd(this,a))));else{a=this.f.L();for(var c=0;c<a.length;c++)b=Ha(b,a[c])}return b};
h.set=function(a,b){S(this);this.H=null;a=Vd(this,a);this.Da(a)&&(this.g=za(this.g)-this.f.get(a).length);this.f.set(a,[b]);this.g=za(this.g)+1;return this};h.get=function(a,b){if(!a)return b;a=this.L(a);return 0<a.length?String(a[0]):b};
h.toString=function(){if(this.H)return this.H;if(!this.f)return"";for(var a=[],b=this.f.ca(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.L(d);for(var f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}}return this.H=a.join("&")};h.clone=function(){var a=new Nd;a.H=this.H;this.f&&(a.f=this.f.clone(),a.g=this.g);return a};var Vd=function(a,b){b=String(b);a.M&&(b=b.toLowerCase());return b};
Nd.prototype.bc=function(a){a&&!this.M&&(S(this),this.H=null,this.f.forEach(function(b,c){var d=c.toLowerCase();c!=d&&(this.remove(c),this.remove(d),0<b.length&&(this.H=null,this.f.set(Vd(this,d),Ia(b)),this.g=za(this.g)+b.length))},this));this.M=a};Nd.prototype.extend=function(a){for(var b=0;b<arguments.length;b++)Fb(arguments[b],function(c,d){this.add(d,c)},this)};var T=function(a){J.call(this);this.headers=new Bb;this.yb=a||null;this.fa=!1;this.xb=this.a=null;this.Pa=this.wc=this.lb="";this.ua=this.Kb=this.kb=this.Gb=!1;this.Va=0;this.tb=null;this.Ic="";this.vb=this.ld=this.fc=!1};w(T,J);var Wd=/^https?$/i,Xd=["POST","PUT"],Yd=[];T.prototype.Yc=function(){this.Eb();Ga(Yd,this)};
T.prototype.send=function(a,b,c,d){if(this.a)throw Error("[goog.net.XhrIo] Object is active with another request="+this.lb+"; newUri="+a);b=b?b.toUpperCase():"GET";this.lb=a;this.Pa="";this.wc=b;this.Gb=!1;this.fa=!0;this.a=this.yb?Fd(this.yb):Fd(Dd);this.xb=this.yb?Cd(this.yb):Cd(Dd);this.a.onreadystatechange=v(this.Cc,this);this.ld&&"onprogress"in this.a&&(this.a.onprogress=v(function(f){this.Bc(f,!0)},this),this.a.upload&&(this.a.upload.onprogress=v(this.Bc,this)));try{M(this.R,U(this,"Opening Xhr")),
this.Kb=!0,this.a.open(b,String(a),!0),this.Kb=!1}catch(f){M(this.R,U(this,"Error opening Xhr: "+f.message));this.gb(5,f);return}a=c||"";var e=this.headers.clone();d&&Fb(d,function(f,g){e.set(g,f)});d=Fa(e.ca());c=m.FormData&&a instanceof m.FormData;!(0<=Ba(Xd,b))||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,g){this.a.setRequestHeader(g,f)},this);this.Ic&&(this.a.responseType=this.Ic);"withCredentials"in this.a&&this.a.withCredentials!==this.fc&&
(this.a.withCredentials=this.fc);try{Zd(this),0<this.Va&&(this.vb=$d(this.a),M(this.R,U(this,"Will abort after "+this.Va+"ms if incomplete, xhr2 "+this.vb)),this.vb?(this.a.timeout=this.Va,this.a.ontimeout=v(this.Nc,this)):this.tb=xd(this.Nc,this.Va,this)),M(this.R,U(this,"Sending request")),this.kb=!0,this.a.send(a),this.kb=!1}catch(f){M(this.R,U(this,"Send error: "+f.message)),this.gb(5,f)}};
var $d=function(a){return Mb&&bc(9)&&ia(a.timeout)&&n(a.ontimeout)},Ea=function(a){return"content-type"==a.toLowerCase()};T.prototype.Nc=function(){"undefined"!=typeof ha&&this.a&&(this.Pa="Timed out after "+this.Va+"ms, aborting",M(this.R,U(this,this.Pa)),this.dispatchEvent("timeout"),this.abort(8))};T.prototype.gb=function(a,b){this.fa=!1;this.a&&(this.ua=!0,this.a.abort(),this.ua=!1);this.Pa=b;ae(this);be(this)};var ae=function(a){a.Gb||(a.Gb=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))};
T.prototype.abort=function(){this.a&&this.fa&&(M(this.R,U(this,"Aborting")),this.fa=!1,this.ua=!0,this.a.abort(),this.ua=!1,this.dispatchEvent("complete"),this.dispatchEvent("abort"),be(this))};T.prototype.i=function(){this.a&&(this.fa&&(this.fa=!1,this.ua=!0,this.a.abort(),this.ua=!1),be(this,!0));T.T.i.call(this)};T.prototype.Cc=function(){this.ia||(this.Kb||this.kb||this.ua?ce(this):this.jd())};T.prototype.jd=function(){ce(this)};
var ce=function(a){if(a.fa&&"undefined"!=typeof ha)if(a.xb[1]&&4==de(a)&&2==ee(a))M(a.R,U(a,"Local request error detected and ignored"));else if(a.kb&&4==de(a))xd(a.Cc,0,a);else if(a.dispatchEvent("readystatechange"),4==de(a)){M(a.R,U(a,"Request complete"));a.fa=!1;try{if(fe(a))a.dispatchEvent("complete"),a.dispatchEvent("success");else{try{var b=2<de(a)?a.a.statusText:""}catch(c){M(a.R,"Can not get status: "+c.message),b=""}a.Pa=b+" ["+ee(a)+"]";ae(a)}}finally{be(a)}}};
T.prototype.Bc=function(a,b){y("progress"===a.type,"goog.net.EventType.PROGRESS is of the same type as raw XHR progress.");this.dispatchEvent(ge(a,"progress"));this.dispatchEvent(ge(a,b?"downloadprogress":"uploadprogress"))};
var ge=function(a,b){return{type:b,lengthComputable:a.lengthComputable,loaded:a.loaded,total:a.total}},be=function(a,b){if(a.a){Zd(a);var c=a.a,d=a.xb[0]?la:null;a.a=null;a.xb=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){(a=a.R)&&a.Lc("Problem encountered resetting onreadystatechange: "+e.message,void 0)}}},Zd=function(a){a.a&&a.vb&&(a.a.ontimeout=null);a.tb&&(m.clearTimeout(a.tb),a.tb=null)};T.prototype.Mb=function(){return!!this.a};
var fe=function(a){var b=ee(a);a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}if(!c){if(b=0===b)a=String(a.lb).match(Gd)[1]||null,!a&&m.self&&m.self.location&&(a=m.self.location.protocol,a=a.substr(0,a.length-1)),b=!Wd.test(a?a.toLowerCase():"");c=b}return c},de=function(a){return a.a?a.a.readyState:0},ee=function(a){try{return 2<de(a)?a.a.status:-1}catch(b){return-1}},he=function(a){try{return a.a?a.a.responseText:""}catch(b){return M(a.R,
"Can not get responseText: "+b.message),""}};T.prototype.getResponseHeader=function(a){if(this.a&&4==de(this))return a=this.a.getResponseHeader(a),null===a?void 0:a};T.prototype.getAllResponseHeaders=function(){return this.a&&4==de(this)?this.a.getAllResponseHeaders()||"":""};var U=function(a,b){return b+" ["+a.wc+" "+a.lb+" "+ee(a)+"]"};new J;new hc;var je=function(a,b,c){function d(g){g&&b.appendChild(q(g)?a.createTextNode(g):g)}for(var e=1;e<c.length;e++){var f=c[e];!na(f)||u(f)&&0<f.nodeType?d(f):Ca(ie(f)?Ia(f):f,d)}},ie=function(a){if(a&&"number"==typeof a.length){if(u(a))return"function"==typeof a.item||"string"==typeof a.item;if(t(a))return"function"==typeof a.item}return!1},ke=function(){this.La=m.document||document};h=ke.prototype;h.getElementsByTagName=function(a,b){return(b||this.La).getElementsByTagName(String(a))};
h.createElement=function(a){return this.La.createElement(String(a))};h.createTextNode=function(a){return this.La.createTextNode(String(a))};h.da=function(){var a=this.La;return a.parentWindow||a.defaultView};h.appendChild=function(a,b){y(null!=a&&null!=b,"goog.dom.appendChild expects non-null arguments");a.appendChild(b)};h.append=function(a,b){var c=a;y(c,"Node cannot be null or undefined.");je(9==c.nodeType?c:c.ownerDocument||c.document,a,arguments)};
h.canHaveChildren=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};h.removeNode=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};
h.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};var le=function(){};var me=function(a,b){this.Qc=!!b};w(me,le);me.prototype.sb=function(a){var b=new ne;oe(this,a,b);return b.toString()};
var oe=function(a,b,c){var d=pb(b.v());Ca(d,function(e){if(b.has(e)){y(e.sa()==b.v(),"The current message does not contain the given field");var f=e.U;f=b.X[f].Nb?null!=b.F[f]?b.F[f].length:0:null!=b.F[f]?1:0;for(var g=0;g<f;++g){c.append(e.getName());11==e.ba||10==e.ba?(c.append(" {"),pe(c),c.ka+=2):c.append(": ");qe(this,b.get(e,g),e,c);if(11==e.ba||10==e.ba)re(c),c.append("}");pe(c)}}},a);rb(b,function(e,f){se(this,e,f,y(c))},a)},se=function(a,b,c,d){if(null!=c)if(r(c))Ca(c,function(g){se(this,
b,g,d)},a);else{if(u(c)){d.append(b);d.append(" {");pe(d);d.ka+=2;if(c instanceof B)oe(a,c,d);else for(var e in c){var f=kb(e);y(isFinite(f)&&0==f%1);se(a,f,c[e],d)}re(d);d.append("}")}else q(c)&&(c=jb(c)),d.append(b),d.append(": "),d.append(c.toString());pe(d)}},qe=function(a,b,c,d){switch(c.ba){case 1:case 2:case 3:case 4:case 5:case 13:case 6:case 7:case 8:case 15:case 16:case 17:case 18:d.append(b);break;case 12:case 9:b=jb(b.toString());d.append(b);break;case 14:if(!a.Qc){var e=!1;La(c.Rb,function(f,
g){e||f!=b||(d.append(g),e=!0)})}e&&!a.Qc||d.append(b.toString());break;case 10:case 11:oe(a,b,d)}},ne=function(){this.ka=0;this.bb=[];this.Zb=!0};ne.prototype.toString=function(){return this.bb.join("")};var re=function(a){a.ka-=2;y(0<=a.ka)};ne.prototype.append=function(a){if(this.Zb){for(var b=0;b<this.ka;++b)this.bb.push(" ");this.Zb=!1}this.bb.push(a.toString())};var pe=function(a){a.bb.push("\n");a.Zb=!0};var te=new me;B.prototype.toString=function(){return te.sb(this)};var ue=new xb,ve=new D;C(ve,1,3);C(ve,2,2);C(ue,1,ve);var we=new D;C(we,1,3);C(we,2,2);var xe=new D;C(xe,1,3);C(xe,2,2);(function(){if(Rb){var a=/Windows NT ([0-9.]+)/;return(a=a.exec(z))?a[1]:"0"}return Qb?(a=/10[_.][0-9_.]+/,(a=a.exec(z))?a[0].replace(/_/g,"."):"10"):Sb?(a=/Android\s+([^\);]+)(\)|;)/,(a=a.exec(z))?a[1]:""):Tb||Ub||Vb?(a=/(?:iPhone|CPU)\s+OS\s+(\S+)/,(a=a.exec(z))?a[1].replace(/_/g,"."):""):""})();var ye=function(a,b,c){E.call(this);this.Pb=a;this.Ga=b||0;this.Fa=c;this.Xc=v(this.$c,this)};w(ye,E);h=ye.prototype;h.P=0;h.i=function(){ye.T.i.call(this);this.stop();delete this.Pb;delete this.Fa};h.start=function(a){this.stop();this.P=xd(this.Xc,n(a)?a:this.Ga)};h.stop=function(){this.Mb()&&m.clearTimeout(this.P);this.P=0};h.Mb=function(){return 0!=this.P};h.$c=function(){this.P=0;this.Pb&&this.Pb.call(this.Fa)};var ze=function(){E.call(this);this.ac={}};w(ze,E);ze.prototype.connect=function(a){a&&a()};ze.prototype.isConnected=function(){return!0};ze.prototype.i=function(){ze.T.i.call(this);delete this.ac;delete this.qc};var K={};var Ae={1:"NativeMessagingTransport",2:"IframePollingTransport",3:"DirectTransport"},Be=["pu","lru","pru","lpu","ppu"],V={},De=function(){for(var a=10,b=Ce,c=b.length,d="";0<a--;)d+=b.charAt(Math.floor(Math.random()*c));return d},Ce="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";var W=function(a){E.call(this);this.qa=a||va||(va=new ke)};w(W,E);W.prototype.dc=0;W.prototype.da=function(){return this.qa.da()};W.prototype.getName=function(){return Ae[String(this.dc)]||""};/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
var X=function(){this.rb=[];this.Ac=void 0;this.pc=null;this.Na=this.K=!1;this.I=void 0;this.cc=this.ic=this.Ab=!1;this.ub=0;this.m=null;this.ab=0};X.prototype.cancel=function(a){if(this.K)this.I instanceof X&&this.I.cancel();else{if(this.m){var b=this.m;delete this.m;a?b.cancel(a):(b.ab--,0>=b.ab&&b.cancel())}this.Ac?this.Ac.call(this.pc,this):this.cc=!0;this.K||this.rc(new Ee(this))}};X.prototype.oc=function(a,b){this.Ab=!1;Fe(this,a,b)};
var Fe=function(a,b,c){a.K=!0;a.I=c;a.Na=!b;Ge(a)},Ie=function(a){if(a.K){if(!a.cc)throw new He(a);a.cc=!1}};X.prototype.J=function(a){Ie(this);Je(a);Fe(this,!0,a)};X.prototype.rc=function(a){Ie(this);Je(a);Fe(this,!1,a)};var Je=function(a){y(!(a instanceof X),"An execution sequence may not be initiated with a blocking Deferred.")},Le=function(a,b,c){Ke(a,b,null,c)},Ke=function(a,b,c,d){y(!a.ic,"Blocking Deferreds can not be re-used");a.rb.push([b,c,d]);a.K&&Ge(a)};
X.prototype.then=function(a,b,c){var d,e,f=new N(function(g,k){d=g;e=k});Ke(this,d,function(g){g instanceof Ee?f.cancel():e(g)});return f.then(a,b,c)};X.prototype.$goog_Thenable=!0;var Me=function(a,b){b instanceof X?Le(a,v(b.Wc,b)):Le(a,function(){return b})};X.prototype.Wc=function(a){var b=new X;Ke(this,b.J,b.rc,b);a&&(b.m=this,this.ab++);return b};
var Ne=function(a){return Da(a.rb,function(b){return t(b[1])})},Ge=function(a){if(a.ub&&a.K&&Ne(a)){var b=a.ub,c=Oe[b];c&&(m.clearTimeout(c.P),delete Oe[b]);a.ub=0}a.m&&(a.m.ab--,delete a.m);b=a.I;for(var d=c=!1;a.rb.length&&!a.Ab;){var e=a.rb.shift(),f=e[0],g=e[1];e=e[2];if(f=a.Na?g:f)try{var k=f.call(e||a.pc,b);n(k)&&(a.Na=a.Na&&(k==b||k instanceof Error),a.I=b=k);if(gd(b)||"function"===typeof m.Promise&&b instanceof m.Promise)d=!0,a.Ab=!0}catch(l){b=l,a.Na=!0,Ne(a)||(c=!0)}}a.I=b;d&&(k=v(a.oc,
a,!0),d=v(a.oc,a,!1),b instanceof X?(Ke(b,k,d),b.ic=!0):b.then(k,d));c&&(b=new Pe(b),Oe[b.P]=b,a.ub=b.P)},He=function(){x.call(this)};w(He,x);He.prototype.message="Deferred has already fired";He.prototype.name="AlreadyCalledError";var Ee=function(){x.call(this)};w(Ee,x);Ee.prototype.message="Deferred was canceled";Ee.prototype.name="CanceledError";var Pe=function(a){this.P=m.setTimeout(v(this.sd,this),0);this.gb=a};
Pe.prototype.sd=function(){y(Oe[this.P],"Cannot throw an error that is not scheduled.");delete Oe[this.P];throw this.gb;};var Oe={};var Re=function(a,b){W.call(this,b);this.h=a;this.Ea=new P(this);ic(this,ta(F,this.Ea));this.Y=new wd(100,this.da());ic(this,ta(F,this.Y));this.B=new X;this.C=new X;this.u=new X;this.Fb=De();this.la=null;this.Ba={};this.kd=this.h.name;Qe(this.h,this.h.name+"_"+Y(this.h));this.Oa=!1;Me(this.u,this.B);Me(this.u,this.C);Le(this.u,this.Sb,this);this.u.J(!0);this.Ea.Qa(this.Y,"tick",this.Ra);L("DirectTransport created. role="+Y(this.h))};w(Re,W);
var Se={},Ve=function(a){var b=new Te(a.channelName,a.service,a.payload);a=b.Bb;var c=b.$b;b=b.Ub;M(K.j,"messageReceived: channel="+a+", service="+c+", payload="+b);var d=V[a];if(d)return d.Za(c,b),!0;d=Ue(b)[0];for(var e in V){var f=V[e];if(1==Y(f)&&!f.isConnected()&&"tp"==c&&"SETUP"==d)return Qe(f,a),f.Za(c,b),!0}L("channel name mismatch; message ignored.");return!1};h=Re.prototype;h.dc=3;
h.Oc=function(a){a=Ue(a);var b=a[1];switch(a[0]){case "SETUP_ACK":this.B.K||this.B.J(!0);break;case "SETUP":this.qb(),null!=this.la&&this.la!=b&&(L("Sending SETUP and changing peer ID to: "+b),this.Ta()),this.la=b}};h.Ta=function(){this.send("tp","SETUP,"+this.Fb)};h.qb=function(){this.send("tp","SETUP_ACK");this.C.K||this.C.J(!0)};
h.connect=function(){var a=this.da();if(a){var b=qa(a);0==(Se[b]||0)&&null==ka("crosswindowmessaging.channel",a)&&ja("crosswindowmessaging.channel",Ve,a);Se[b]++;this.Oa=!0;this.Ra()}else M(K.j,"connect(): no window to initialize.")};h.Ra=function(){this.h.isConnected()?this.Y.stop():(this.Y.start(),this.Ta())};h.send=function(a,b){this.h.N?(a=new Te(this.kd+"_"+(0==Y(this.h)?1:0),a,b),this.h.o.directSyncMode?this.sc(a):this.Ba[qa(a)]=xd(v(this.sc,this,a),0)):M(K.j,"send(): window not ready")};
h.sc=function(a){var b=qa(a);this.Ba[b]&&delete this.Ba[b];try{var c=ka("crosswindowmessaging.channel",this.h.N)}catch(d){(a=K.j)&&a.na("Can't access other window, ignoring.",d);return}if(null===c)(a=K.j)&&a.na("Peer window had no global function.",void 0);else try{c({channelName:a.Bb,service:a.$b,payload:a.Ub}),L("send(): channelName="+a.Bb+" service="+a.$b+" payload="+a.Ub)}catch(d){(a=K.j)&&a.na("Error performing call, ignoring.",d)}};h.Sb=function(){We(this.h,0)};
h.i=function(){if(this.Oa){var a=this.da(),b=qa(a);1==--Se[b]&&ja("crosswindowmessaging.channel",null,a)}this.Ba&&(La(this.Ba,function(c){m.clearTimeout(c)}),this.Ba=null);this.B&&(this.B.cancel(),delete this.B);this.C&&(this.C.cancel(),delete this.C);this.u&&(this.u.cancel(),delete this.u);Re.T.i.call(this)};var Ue=function(a){a=a.split(",");a[1]=a[1]||null;return a},Te=function(a,b,c){this.Bb=a;this.$b=b;this.Ub=c};var Z=function(a,b,c,d,e){W.call(this,c);this.h=a;this.S=e||2;y(1<=this.S);y(2>=this.S);this.Dc=b||"*";this.Ea=new P(this);this.Y=new wd(100,this.da());this.nb=!!d;this.B=new X;this.C=new X;this.u=new X;this.Fb=De();this.la=null;this.nb?1==Y(this.h)?Me(this.u,this.B):Me(this.u,this.C):(Me(this.u,this.B),2==this.S&&Me(this.u,this.C));Le(this.u,this.Sb,this);this.u.J(!0);this.Ea.Qa(this.Y,"tick",this.Ra);L("NativeMessagingTransport created.  protocolVersion="+this.S+", oneSidedHandshake="+this.nb+", role="+
Y(this.h))};w(Z,W);Z.prototype.D=null;Z.prototype.Oa=!1;Z.prototype.dc=1;var Xe={};Z.prototype.Ua=0;
var $e=function(a){var b=a.ja.data;if(!q(b))return!1;var c=b.indexOf("|"),d=b.indexOf(":");if(-1==c||-1==d)return!1;var e=b.substring(0,c);c=b.substring(c+1,d);b=b.substring(d+1);M(K.j,"messageReceived: channel="+e+", service="+c+", payload="+b);if(d=V[e])return d.Za(c,b,a.ja.origin),!0;d=Ye(b)[0];for(var f in V){var g=V[f];if(1==Y(g)&&!g.isConnected()&&"tp"==c&&("SETUP"==d||"SETUP_NTPV2"==d)&&Ze(g,a.ja.origin))return Qe(g,e),g.Za(c,b),!0}L('channel name mismatch; message ignored"');return!1};
Z.prototype.Oc=function(a){var b=Ye(a);a=b[1];switch(b[0]){case "SETUP_ACK":af(this,1);this.B.K||this.B.J(!0);break;case "SETUP_ACK_NTPV2":2==this.S&&(af(this,2),this.B.K||this.B.J(!0));break;case "SETUP":af(this,1);this.qb(1);break;case "SETUP_NTPV2":2==this.S&&(b=this.D,af(this,2),this.qb(2),1!=b&&null==this.la||this.la==a||(L("Sending SETUP and changing peer ID to: "+a),this.Ta()),this.la=a)}};
Z.prototype.Ta=function(){y(!(1==this.S&&2==this.D));2!=this.S||null!=this.D&&2!=this.D||this.send("tp","SETUP_NTPV2,"+this.Fb);null!=this.D&&1!=this.D||this.send("tp","SETUP")};Z.prototype.qb=function(a){y(1!=this.S||2!=a,"Shouldn't try to send a v2 setup ack in v1 mode.");if(2!=this.S||null!=this.D&&2!=this.D||2!=a){if(null!=this.D&&1!=this.D||1!=a)return;this.send("tp","SETUP_ACK")}else this.send("tp","SETUP_ACK_NTPV2");this.C.K||this.C.J(!0)};
var af=function(a,b){b>a.D&&(a.D=b);1==a.D&&(a.C.K||a.nb||a.C.J(!0),a.la=null)};h=Z.prototype;h.connect=function(){var a=this.da(),b=qa(a),c=Xe[b];ia(c)||(c=0);0==c&&Ac(a.postMessage?a:a.document,"message",$e,!1,Z);Xe[b]=c+1;this.Oa=!0;this.Ra()};h.Ra=function(){var a=0==Y(this.h);this.nb&&a||this.h.isConnected()||this.ia?this.Y.stop():(this.Y.start(),this.Ta())};
h.send=function(a,b){var c=this.h.N;c?(this.send=function(d,e){var f=this,g=this.h.name;this.Ua=xd(function(){f.Ua=0;try{var k=c.postMessage?c:c.document;if(k.postMessage)k.postMessage(g+"|"+d+":"+e,f.Dc),M(K.j,"send(): service="+d+" payload="+e+" to hostname="+f.Dc);else{var l=K.j;l&&l.na("Peer window had no postMessage function.",void 0)}}catch(p){(k=K.j)&&k.na("Error performing postMessage, ignoring.",p)}},0)},this.send(a,b)):M(K.j,"send(): window not ready")};
h.Sb=function(){We(this.h,1==this.S||1==this.D?200:void 0)};h.i=function(){if(this.Oa){var a=this.da(),b=qa(a),c=Xe[b];Xe[b]=c-1;1==c&&Hc(a.postMessage?a:a.document,"message",$e,!1,Z)}this.Ua&&(m.clearTimeout(this.Ua),this.Ua=0);F(this.Ea);delete this.Ea;F(this.Y);delete this.Y;this.B.cancel();delete this.B;this.C.cancel();delete this.C;this.u.cancel();delete this.u;delete this.send;Z.T.i.call(this)};var Ye=function(a){a=a.split(",");a[1]=a[1]||null;return a};var cf=function(a,b){ze.call(this);for(var c=0,d;d=Be[c];c++)if(d in a&&!/^https?:\/\//.test(a[d]))throw Error("URI "+a[d]+" is invalid for field "+d);this.o=a;this.name=this.o.cn||De();this.qa=b||va||(va=new ke);this.fb=[];this.Vb=new P(this);a.lpu=a.lpu||Hd(this.qa.da().location.href)+"/robots.txt";a.ppu=a.ppu||Hd(a.pu||"")+"/robots.txt";V[this.name]=this;Jc(window,"unload",bf)||zc(window,"unload",bf);L("CrossPageChannel created: "+this.name)};w(cf,ze);var df=/^%*tp$/,ef=/^%+tp$/;h=cf.prototype;
h.ha=null;h.xa=null;h.W=null;h.b=1;h.isConnected=function(){return 2==this.b};h.N=null;h.jb=null;h.connect=function(a){this.Cb=a||la;3==this.b&&(this.b=1);this.xa?Le(this.xa,this.nc):this.nc()};
h.nc=function(){L("continueConnection_()");this.xa=null;if(this.o.ifrid){var a=this.o.ifrid;this.jb=q(a)?this.qa.La.getElementById(a):a}this.jb&&((a=this.jb.contentWindow)||(a=window.frames[this.o.ifrid]),this.N=a);if(!this.N){if(window==window.top)throw Error("CrossPageChannel: Can't connect, peer window-object not set.");this.N=window.parent}if(!this.W){this.o.tp||(this.o.tp=t(document.postMessage)||t(window.postMessage)||Mb&&window.postMessage?1:0);if(t(this.o.tp))this.W=new this.o.tp(this,this.qa);
else switch(this.o.tp){case 1:this.W=new Z(this,this.o.ph,this.qa,!!this.o.osh,this.o.nativeProtocolVersion||2);break;case 3:if(a=this.N)try{a=window.document.domain==this.N.document.domain}catch(b){a=!1}a?this.W=new Re(this,this.qa):L("DirectTransport not supported for this window, peer window in different security context or not set yet.")}if(this.W)L("Transport created: "+this.W.getName());else throw Error("CrossPageChannel: No suitable transport found! You may try injecting a Transport constructor directly via the channel config object.");
}for(this.W.connect();0<this.fb.length;)this.fb.shift()()};h.close=function(){this.xa&&(this.xa.cancel(),this.xa=null);this.fb.length=0;this.Vb.Sa();this.b=3;F(this.W);this.Cb=this.W=null;F(this.ha);this.ha=null;L('Channel "'+this.name+'" closed')};var We=function(a,b){a.isConnected()||a.ha&&a.ha.Mb()||(a.b=2,L('Channel "'+a.name+'" connected'),F(a.ha),n(b)?(a.ha=new ye(a.Cb,b),a.ha.start()):(a.ha=null,a.Cb()))};
cf.prototype.send=function(a,b){if(this.isConnected()){try{var c=!!this.N&&!this.N.closed}catch(d){c=!1}c?(u(b)&&(b=(new Pc).sb(b)),this.W.send(ff(a),b)):((a=K.j)&&a.Lc("Peer has disappeared.",void 0),this.close())}else(a=K.j)&&a.Lc("Can't send. Channel not connected.",void 0)};
cf.prototype.Za=function(a,b,c){if(this.xa)this.fb.push(v(this.Za,this,a,b,c));else if(Ze(this,c))if(this.ia||3==this.b)(b=K.j)&&b.na("CrossPageChannel::xpcDeliver(): Channel closed.",void 0);else if(a&&"tp"!=a)if(this.isConnected()){if(c=a.replace(/%[0-9a-f]{2}/gi,decodeURIComponent),c=ef.test(c)?c.substring(1):c,a=this.ac[c],a||(this.qc?a={J:ta(this.qc,c),zc:u(b)}:((a=this.j)&&a.na('Unknown service name "'+c+'"',void 0),a=null)),a){a:{var d=a.zc;if(d&&q(b))try{var e=JSON.parse(b);break a}catch(f){(e=
this.j)&&e.na("Expected JSON payload for "+c+', was "'+b+'"',void 0);e=null;break a}else if(!d&&!q(b)){e=(new Pc).sb(b);break a}e=b}null!=e&&a.J(e)}}else L("CrossPageChannel::xpcDeliver(): Not connected.");else this.W.Oc(b);else(b=K.j)&&b.na('Message received from unapproved origin "'+c+'" - rejected.',void 0)};
var ff=function(a){df.test(a)&&(a="%"+a);return a.replace(/[%:|]/g,encodeURIComponent)},Y=function(a){var b=a.o.role;return ia(b)?b:window.parent==a.N?1:0},Qe=function(a,b){M(K.j,"changing channel name to "+b);delete V[a.name];a.name=b;V[b]=a},Ze=function(a,b){var c=a.o.ph;return/^[\s\xa0]*$/.test(null==b?"":String(b))||/^[\s\xa0]*$/.test(null==c?"":String(c))||b==a.o.ph};cf.prototype.i=function(){this.close();this.jb=this.N=null;delete V[this.name];F(this.Vb);delete this.Vb;cf.T.i.call(this)};
var bf=function(){for(var a in V)F(V[a])};var gf=function(a,b,c,d,e){a=new Q(a);0!=b&&(R(a),a.A.set("authuser",b));null!=c&&(R(a),a.A.set("pageId",c));null!=d&&(R(a),a.A.set("service",d));this.pd=a.toString();this.ta=e;this.hd=0};gf.prototype.start=function(){};gf.prototype.send=function(a,b,c){var d=new Q(this.pd);for(g in c){var e=g,f=c[g];R(d);d.A.set(e,f)}c=d.toString();d=v(this.uc,this,this.hd++);var g=new T;Yd.push(g);d&&g.Qa("complete",d);g.Ob("ready",g.Yc);g.fc=!0;g.send(c,"POST",a,b)};
gf.prototype.uc=function(a,b){b=b.target;fe(b)?this.ta.pa.send("ss",[a]):(b=he(b),this.ta.pa.send("sf",[a,b]))};var hf=function(a,b,c,d,e){this.ed=new gf(a,b,c,d,this);a=new Q(e||window.location.href);this.wd=JSON.parse(a.A.get("xpc")||"");this.pa=null};hf.prototype.Lb=function(){this.pa=new cf(this.wd);var a=v(hf.prototype.send,this);this.pa.ac.s={J:a,zc:!0};this.pa.connect()};hf.prototype.send=function(a){this.ed.send(a[0],a[1],a[2])};hf.prototype.uc=function(a,b){b=b.target;fe(b)?this.pa.send("ss",[a]):this.pa.send("sf",[a,he(b)])};hf.prototype.init=hf.prototype.Lb;ja("invalidation.XpcSenderServer",hf,void 0);
